version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/SysTest_Part1
    steps:
      - checkout
      - run:
          name: "run tests"
          command: python -m pytest -v --cov

workflows:
  version: 2
  build:
    jobs:
      - build